### ISSUE TITLE
Some code redundancy in the onChangeTab function in TimeTableActivity.java

### ISSUE THREAD

**Issue by yk1ax** [GOVINDDIXIT/IIITL-Student-APP#135]
@refactor-droidyy The change that I intend to make removes almost 30 extra lines of code

**Comment by refactor-droidyy** [comment]
@yk1ax go on creating a common function.

**Comment by yk1ax** [comment]
@refactor-droidyy In the onChangeTab function what's the use of the AnyDay.getResources().getColor(R.color.any_color) 
I had speculation about what it does and I got nothing that seems of use over there and I ran the program after wrapping all these statements in comments and the app seemed to be running still the same

**Comment by refactor-droidyy** [comment]
@yk1ax its because when you are using  **Tue.getResources().getColor(R.color.light_color)** you are only getting a id for that colour that is defined in colors.xml you have to make a slight change use  **Tue.setTextColor(getResources().getColor(R.color.light_color))** to it will set the text color of day test in the tab Bar with some color variation so that the user can see which day schedule you are viewing.
